### PR TITLE
UI

### PR DESCRIPTION
**Pull request by tushitshukla03**
updated login and signup pages

### CODE REVIEW

**Comment by Priyansh61** [comment]
Hey @tushitshukla03, Thanks for the efforts

can we bring some similarities btwn Project page and home page

image

Like instead of having all black we can use the project page color

image

Also can you check the cards in the project page make sure they all have the explore button at the same place, like right now its all zig zag
image


And somewhat try to match the card color with the theme of the site, like can you think of  a way where we can use yellow in our site more ?

image


Please change the color of the sidebar 

image


Also can we update the color of the loader to match our theme?

image

Last please compress the size of the assets, like on the prod site it takes forever to load 

Thanks,

**Comment by tushitshukla03** [comment]
ui updates

**Comment by Priyansh61** [comment]
@tushitshukla03  Please fix the links of the explore button, these are not working as expected

image

And also please change the sidebar scroller colour

**Comment by tushitshukla03** [comment]
> @tushitshukla03 Please fix the links of the explore button, these are not working as expected
> 
> image
> 
> And also please change the sidebar scroller colour
 done

**Pull request merged**
