### PR TITLE
compressed logo

### PR DESCRIPTION
**Pull request by anshikkay**
@Priyansh61 
I have made the changes, suggest me if any changes need to be made.

### CODE REVIEW

**Comment by anshikkay** [comment]
#35

**Comment by Priyansh61** [comment]
@anshikkay Can we compress it further ?

**Comment by anshikkay** [comment]
@Priyansh61 
sure !!

**Comment by Priyansh61** [comment]
Great Job @anshikkay

**Comment by anshikkay** [comment]
@Priyansh61

**Pull request merged**
