### PR TITLE
fix: Fixed the issue in dashboard page

### LINKED ISSUE #59: [BUG]: Dashboard page not opening
### Describe the bug

Dashboard page in the **BSoC Website** is not opening. 

### Steps To Reproduce

_No response_

### Expected Behavior

The Dashboard page should open and display the user data.

### Screenshots/Videos

_No response_

### What device are you using?

Desktop, Mobile

### Operating System

_No response_

### What browsers are you seeing the problem on?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Doraemon012**
## Overview

1. This PR fixes #59 
2. This PR does the following: Now, the dashboard page is loading properly.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/BSoC-Website/assets/116624667/44ea933c-4f27-4183-a16e-b35d99f0770b

### CODE REVIEW

**Comment by Doraemon012** [comment]
@Priyansh61 Sir, I have fixed the issue. Please check it.

**Comment by Priyansh61** [comment]
@Doraemon012 I am merging this for now, since it needed urgently. But I am still unsure regarding why we need to add the condition there, when it used to work just fine earlier.

is it related to the delete PR we recently merged and it may be doing something strange to the DB?

WDYT? Can you do some debugging on this issue, since I am thinking we haven't fixed the root cause of this issue?

And thanks for the urgent fix. :)

**Comment by Doraemon012** [comment]
@Priyansh61 Sir, I think someone deleted or changed all of his/ her data (displayName, uid, time, numberOfPrs, score and time) from the `userStats-2023` collection but the empty document is remaining.

**This was the error:**
image


**This is the line of code (`Dashboard.vue` - line 78)**
image

This code is returning an object which contains the doc (i.e. the user data object), and the time. This code isn't checking if the doc contains the required data. 
Since the doc does not contain time, the code is throwing an error that `doc.time is undefined.`


**This is the doc (user data) :**
Screenshot from 2023-07-24 13-12-49

Other doc objects contain information of the users but this one contains the `profilePhotoUrl`. This is the link of the profile image: 


### My changes
Screenshot from 2023-07-24 13-25-10

 Here, I just checked if the doc contains displayName and uid. Since someone cannot signup without displayName and if someone has signed up in the website the, he/she must have an uid.
 
I thought that I should not change the original database, so I just added an if-condition here. 
I think, we can just delete this object from the firestore database to eleminate the root cause of the issue.

**Comment by Doraemon012** [comment]
@Priyansh61 Sir, now I found the actual reason.

Someone tested this code on the actual firestore database. 
Screenshot from 2023-07-24 20-26-59



As we can see, in the `saveProfilePhotoUrl` function, the `.set` method is used. Because of this, the data in `usersRef` is set to `profilePhotoUrl`.



As we know, the `.set` method is used to **create a new document** or to **overwrite** an existing one.
Screenshot from 2023-07-24 20-37-29




May be, this function was tested on the actual database. So, we had this object in the `userStats-2023`. 
Screenshot from 2023-07-24 13-12-49
As, it contains only the `profilePhotoUrl` and the not the required data, we were getting the error that `doc.time is undefined`.

**Comment by Priyansh61** [comment]
That's some amazing work there!! Fantastic Job Neyati

**Pull request merged**
