### PR TITLE
Hamburger

### PR DESCRIPTION
**Pull request by abansal15**
## Overview

1. This PR fixes or fixes part of #33 .
2. This PR does the following: Made Hamburger

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct
image
image

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by abansal15** [comment]
WhatsApp Image 2023-06-17 at 11 13 05
mobile view

**Comment by abansal15** [comment]
@Priyansh61 what changes i should do in the above code so that the background color of the body changes to black while opening the hamburger. Now the items are in the center of the body but the color of the body is not changing to black ??

**Comment by Priyansh61** [comment]
@prernadabi23 @thejaysharma Can you help?

**Comment by thejaysharma** [comment]
@abansal15 Don't make these kinds of straightforward things so complicated. Make a div with full screen and write a logic to show and close for the mobile devices.
for reference you can check it https://codepen.io/andreykrokhin/pen/mGEqja

**Comment by abansal15** [comment]
@Priyansh61  added the hamburger as per you direct me 
image

**Comment by abansal15** [comment]
@Priyansh61 is it okk or i have to make some more changes ?

**Comment by thejaysharma** [comment]
@abansal15 The background should be the same navy blue as the theme. The hamburger menu will be on the top right. The colour of the text and Hamburger should be white.
Screenshot_20230704_161949
Screenshot_20230704_161924

**Comment by abansal15** [comment]
image

**Comment by abansal15** [comment]
done the required changes

**Comment by thejaysharma** [comment]
@abansal15 change background colour to #19192a. And place the Hamburger menu after login signup option.

**Comment by abansal15** [comment]
done the required changes 
image

**Comment by abansal15** [comment]
Now is it okk ? @thejaysharma

**Comment by abansal15** [comment]
image

**Comment by abansal15** [comment]
@thejaysharma Any more changes do you want ??

**Comment by prernadabi23** [comment]
@abansal15 The position of the hamburger should be at the rightmost end.

How can the user submit a PR before logging in? The hamburger should only display the home, dashboard, project, login, and signup buttons. After the user logs in, the logout option should be added along with other options.

If you still have any doubts, you can ask them here.

Screenshot from 2023-07-06 18-33-33

**Comment by abansal15** [comment]
@prernadabi23 hamburger is already at the right side ?? What changes I should do  ?  Can you please brief the required changes I should do ...

**Comment by prernadabi23** [comment]
@abansal15 
1. Before the user logs in, the "MyPR" and "Submit PR" options are not needed, so they should be removed.
2. After the user logs in, the logout button should be added to the hamburger menu along with other options.
3. The navbar should only display the Bsoc logo and the hamburger menu; no other elements should be present.

The hamburger options should be different before and after the user logs in.


Screenshot from 2023-07-06 21-16-07

**Comment by abansal15** [comment]
image

**Comment by abansal15** [comment]
In the latest pr the problem of not viewing the login card on clicking it was solved

**Comment by prernadabi23** [comment]
Screenshot from 2023-07-07 12-04-22

The alignment in the desktop view is disturbed. Please correct it to resemble the image below.

Screenshot from 2023-07-07 12-04-25

And this cross option.


WhatsApp Image 2023-07-07 at 12 07 21

**Comment by abansal15** [comment]
@prernadabi23 what i have to do with the cross option ??

**Comment by prernadabi23** [comment]
@abansal15 It shouldn't be present on the login screen.

**Comment by abansal15** [comment]
@prernadabi23 how can i remove the cross sign it is a part of hamburger and login is inside the hamburger therefore the cross sign will come ?

**Comment by abansal15** [comment]
@prernadabi23 i have aligned the items properly and redirect the login page to the project section as if i redirect it to home then it wont work as we are alraedy on the home page therefore i redirected it to projects section.

**Comment by abansal15** [comment]
@prernadabi23 now is it okk ?

**Comment by abansal15** [comment]
@prernadabi23 ?

**Comment by prernadabi23** [comment]
@abansal15 Yes, let other members also review, and then we will merge.
@thejaysharma @tushitshukla03 .

**Comment by abansal15** [comment]
okk @prernadabi23 . I also request  @thejaysharma and @tushitshukla03 to review the issue..

**Comment by thejaysharma** [comment]
LGTM! :)

**Comment by abansal15** [comment]
@tushitshukla03 ?

**Review by Priyansh61 — CHANGES_REQUESTED** [review]
@abansal15 While going through the preview I noticed the login / signup button are still clickable when you click on the button for the navbar, like the buttons are hidden there just not visible, so can you please fix that?



Also the bsoc logo is not alligned with the bsoc image PTAL...

https://github.com/bsoc-bitbyte/BSoC-Website/assets/96513964/8f0307a5-5af8-4c83-ba2c-76b535621d2b

**Comment by abansal15** [comment]
@Priyansh61 bsoc logo is now properly aligned and the hidden button problem is solved i do the display none previously its opacity was setted to 0.
image

**Comment by abansal15** [comment]
@Priyansh61 please review the changes...

**Review by Priyansh61 — CHANGES_REQUESTED** [review]
@abansal15 last small nits

the spacing around the logo is very compact currently, distribute it properly

image

**Comment by abansal15** [comment]
@Priyansh61 added equal spacing in the logo. Hope it is now ok?
image

**Review by Priyansh61 — CHANGES_REQUESTED** [review]
@abansal15 Please see for `home` and `project` button when you click on them it complete reloads the page, see how we use vue-router and use them. Currently you are using anchor tags for routing

**Comment by abansal15** [comment]
@Priyansh61 what is the problem i am not able to understand . I Think the site is working properly ?

**Comment by abansal15** [comment]
@Priyansh61 home and project buttons are working properly . Then what is the issue can you please explain the issue in brief ?

**Comment by thejaysharma** [comment]
Properly align all the items horizontally. 
Screenshot_20230710_233627

**Comment by abansal15** [comment]
@thejaysharma aligned the items
image

**Comment by abansal15** [comment]
> @abansal15 Please see for `home` and `project` button when you click on them it complete reloads the page, see how we use vue-router and use them. Currently you are using anchor tags for routing

solved the issue please review it

**Review by Priyansh61 — APPROVED** [review]
LGTM! @prernadabi23 @thejaysharma Can you please assign the difficulty tag!

**Comment by Priyansh61** [comment]
PTAL @prernadabi23 @thejaysharma And merge this one

**Comment by thejaysharma** [comment]
LGTM!

**Review by thejaysharma — APPROVED** [review]

**Pull request merged**
