### PR TITLE
feat(frontend): Update project card views(#109)

### PR DESCRIPTION
**Pull request by tanishkaa08**
## Overview

1. This PR fixes or fixes part of #109 .
2. This PR does the following: [updated Project cards according to the new theme of the website]

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by tanishkaa08** [comment]
Screenshot 2024-07-15 195958

**Comment by tanishkaa08** [comment]
Screenshot 2024-07-15 201006

**Comment by ramG-reddy** [comment]
@tanishkaa08 Your code and logic looks good however, the following changes are required
- The explore button would look better if it is placed at the right bottom with bigger size
- Add the text "Maintained by" on closed state above the maintainers names
- Handle the font sizes on mobile devices properly it feels small
- Increase the font size of the description accordingly such that an average description covers the height of the card, Add an overflow scroll to just the description in case any  project has a longer description
- Use minor color for the hover effect of the explore button

**Comment by tanishkaa08** [comment]
Made the changes Required.

**Comment by ramG-reddy** [comment]
@tanishkaa08 looks good, just some minor changes are required.

image

- As you could see the description content doesn't have padding which doesn't look good.
- Padding for explore button on mobiles.
- It looks like the whole inner content is not centered, could tell that from the difference of the gaps of the description box on either side, center them.

**Pull request closed without merging**
