### PR TITLE
fixed login/signup cards allignment

### PR DESCRIPTION
**Pull request by prateekjha1204**
## Overview

1. This PR fixes or fixes part of [BUG]: Login / Signup Cards not aligned properly in mobile displays #34.
2. This PR does the following: It properly aligns the Login/SingUp card.

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

Properly aligned SignUp card
Screenshot (21)

Properly aligned Login card
Screenshot (22)

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Priyansh61** [comment]
@prateekjha1204 The cross button gets misaligned on smaller screens can you please fix that??

image

**Comment by prateekjha1204** [comment]
@Priyansh61 Fixed the cross button misaligned on smaller screens

**Review by Priyansh61 — APPROVED** [review]
Fast and Amazing Work @prateekjha1204  :+1:

**Comment by prateekjha1204** [comment]
Thank you Sir

**Comment by prateekjha1204** [comment]
> Fast and Amazing Work @prateekjha1204 +1

Thank you Sir

**Pull request merged**
